git:
  pagers:
    - colorArg: always
      pager: |
        if [ -n "$NVIM" ]; then
            delta --syntax-theme="Visual Studio Dark+" --paging=never
        else
            delta --paging=never
        fi
  overrideGpg: true
gui:
  nerdFontsVersion: "3"
  useHunkModeInStagingView: true
